[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "telemetry-python"
version = "0.1.0"
dependencies = [
    "pyserial",
    "cantools",
    "python-can",
    "digi-xbee"
]
