[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "telemetry-python"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pyserial",
    "cantools",
    "python-can",
    "digi-xbee",
    "psycopg2",
    "SQLAlchemy"
]
